<?php

namespace Database\Seeders;

use App\Models\JobCategory;
use App\Models\TenderAd;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class TenderAdSeeder extends Seeder
{
    public function run(): void
    {
        TenderAd::query()->delete();

        $categories = JobCategory::pluck('id')->toArray();
        $catId = $categories[0] ?? null;
        $today = Carbon::today();

        $tenders = [
            [
                'title' => 'Supply of Medical Equipment and Supplies',
                'description' => 'Procurement of medical equipment and consumables for regional health facilities. Bidders must be registered suppliers with relevant certifications.',
                'summary' => 'Procurement of essential medical equipment and consumables for 15 county health facilities.',
                'scope_of_work' => 'Supply of various medical equipment including patient monitors, ultrasound machines, laboratory equipment, surgical instruments, and consumables. All items must meet international quality standards.',
                'requirements' => [
                    'Licensed medical equipment supplier',
                    'WHO/FDA approved products',
                    'Local presence or authorized distributor',
                ],
                'reference_number' => 'TND-2026-003-MED',
                'tender_type' => 'RFQ',
                'entity_name' => 'Ministry of Health',
                'sector' => 'Medical Supplies',
                'procuring_entity' => 'Kenya Medical Supplies Authority',
                'country_region' => 'Kenya',
                'location' => 'Multiple Counties, Kenya',
                'start_date' => $today->copy()->subDays(10)->toDateString(),
                'end_date' => $today->copy()->addDays(5)->toDateString(),
                'amount' => 1350000,
                'budget_min' => 1200000,
                'budget_max' => 1500000,
                'currency' => 'USD',
                'submission_method' => 'Online portal submission only',
                'required_documents' => [
                    'Product catalogues and specifications',
                    'Price quotations',
                    'Authorization letters from manufacturers',
                    'Quality certificates',
                    'Delivery schedule',
                ],
                'eligibility_criteria' => [
                    'Licensed medical equipment supplier',
                    'WHO/FDA approved products',
                    'Local presence or authorized distributor',
                    'After-sales service capability',
                ],
                'attachments' => [
                    ['id' => '1', 'name' => 'Equipment_List.pdf', 'type' => 'PDF', 'size' => '1.1 MB', 'url' => '/documents/tenders/equipment-list.pdf'],
                    ['id' => '2', 'name' => 'Technical_Requirements.pdf', 'type' => 'PDF', 'size' => '980 KB', 'url' => '/documents/tenders/technical-requirements.pdf'],
                    ['id' => '3', 'name' => 'Delivery_Schedule.xlsx', 'type' => 'Excel', 'size' => '234 KB', 'url' => '/documents/tenders/delivery-schedule.xlsx'],
                ],
                'published_date' => $today->copy()->subDays(10)->toDateString(),
                'clarification_deadline' => $today->copy()->addDays(2)->toDateString(),
                'submission_deadline' => $today->copy()->addDays(5)->toDateString(),
                'status' => 'active',
                'views_count' => 342,
                'applications_count' => 18,
            ],
            [
                'title' => 'Environmental Impact Assessment Study',
                'description' => 'Conduct comprehensive EIA for proposed infrastructure project. Consultant with environmental certification and local experience preferred.',
                'summary' => 'Full environmental impact assessment for the proposed Nairobi-Mombasa highway expansion project.',
                'scope_of_work' => 'Conduct baseline environmental surveys, stakeholder consultations, impact prediction and evaluation, mitigation measures development, and preparation of EIA report for submission to NEMA.',
                'requirements' => [
                    'NEMA-registered EIA expert',
                    'Minimum 10 years environmental consulting experience',
                    'Previous EIA for infrastructure projects',
                ],
                'reference_number' => 'TND-2026-012-EIA',
                'tender_type' => 'RFP',
                'entity_name' => 'NEMA',
                'sector' => 'Consulting Services',
                'procuring_entity' => 'National Environment Management Authority',
                'country_region' => 'Kenya',
                'location' => 'Nairobi, Kenya',
                'start_date' => $today->copy()->subDays(5)->toDateString(),
                'end_date' => $today->copy()->addMonths(3)->toDateString(),
                'amount' => 525000,
                'budget_min' => 450000,
                'budget_max' => 600000,
                'currency' => 'USD',
                'submission_method' => 'Physical and electronic submission',
                'required_documents' => [
                    'Company profile and NEMA registration',
                    'CVs of key personnel',
                    'Technical proposal',
                    'Financial proposal (separate sealed envelope)',
                    'References from previous EIA projects',
                ],
                'eligibility_criteria' => [
                    'NEMA-registered EIA expert firm',
                    'At least 5 completed EIA reports for infrastructure projects',
                    'Team lead with PhD or MSc in Environmental Science',
                    'Valid tax compliance certificate',
                ],
                'attachments' => [
                    ['id' => '1', 'name' => 'Project_Brief.pdf', 'type' => 'PDF', 'size' => '2.3 MB', 'url' => '/documents/tenders/project-brief.pdf'],
                    ['id' => '2', 'name' => 'ToR_EIA_Study.pdf', 'type' => 'PDF', 'size' => '1.5 MB', 'url' => '/documents/tenders/tor-eia-study.pdf'],
                ],
                'published_date' => $today->copy()->subDays(5)->toDateString(),
                'clarification_deadline' => $today->copy()->addWeeks(6)->toDateString(),
                'submission_deadline' => $today->copy()->addMonths(3)->toDateString(),
                'status' => 'active',
                'views_count' => 189,
                'applications_count' => 7,
            ],
            [
                'title' => 'Food and Supplies Distribution Contract',
                'description' => 'Long-term contract for supply and distribution of food and non-food items to designated distribution centres across the country.',
                'summary' => 'Three-year framework contract for nationwide food and essential supplies distribution to 47 county distribution centres.',
                'scope_of_work' => 'Warehousing, transportation, last-mile delivery, and inventory management of food and non-food relief items. Includes cold chain management for perishable goods and real-time tracking of all shipments.',
                'requirements' => [
                    'Registered logistics/distribution company',
                    'Fleet of at least 50 distribution vehicles',
                    'Warehousing capacity of 10,000+ sqm',
                    'Cold chain logistics capability',
                ],
                'reference_number' => 'TND-2026-015-FSD',
                'tender_type' => 'ITB',
                'entity_name' => 'NDMA',
                'sector' => 'Food & Supplies',
                'procuring_entity' => 'National Drought Management Authority',
                'country_region' => 'Kenya',
                'location' => 'Nationwide',
                'start_date' => $today->copy()->subDays(3)->toDateString(),
                'end_date' => $today->copy()->addMonths(2)->addWeeks(2)->toDateString(),
                'amount' => 2250000,
                'budget_min' => 2000000,
                'budget_max' => 2500000,
                'currency' => 'USD',
                'submission_method' => 'Online portal submission only',
                'required_documents' => [
                    'Certificate of incorporation',
                    'Fleet inventory and ownership proof',
                    'Warehouse lease agreements or ownership',
                    'Financial statements (last 3 years)',
                    'Distribution network map',
                    'Health and safety compliance certificates',
                ],
                'eligibility_criteria' => [
                    'Minimum 5 years in logistics/distribution',
                    'Annual turnover of at least $1M',
                    'Nationwide distribution capability',
                    'Valid KEBS and public health certifications',
                    'No pending litigation with government',
                ],
                'attachments' => [
                    ['id' => '1', 'name' => 'Distribution_Requirements.pdf', 'type' => 'PDF', 'size' => '3.2 MB', 'url' => '/documents/tenders/distribution-requirements.pdf'],
                    ['id' => '2', 'name' => 'County_Centres_List.xlsx', 'type' => 'Excel', 'size' => '156 KB', 'url' => '/documents/tenders/county-centres-list.xlsx'],
                    ['id' => '3', 'name' => 'SLA_Template.pdf', 'type' => 'PDF', 'size' => '890 KB', 'url' => '/documents/tenders/sla-template.pdf'],
                ],
                'published_date' => $today->copy()->subDays(3)->toDateString(),
                'clarification_deadline' => $today->copy()->addWeeks(5)->toDateString(),
                'submission_deadline' => $today->copy()->addMonths(2)->addWeeks(2)->toDateString(),
                'status' => 'active',
                'views_count' => 456,
                'applications_count' => 23,
            ],
            [
                'title' => 'Communities and Infrastructure Development',
                'description' => 'Design and supervision of community infrastructure including roads, water points, and sanitation facilities in selected regions.',
                'summary' => 'Design, build, and supervise community infrastructure in 8 underserved sub-counties in the Eastern region.',
                'scope_of_work' => 'Construction of 12 km of access roads, 25 water points (boreholes and shallow wells), 10 public sanitation blocks, and 3 community centres. Includes engineering design, construction supervision, and community engagement.',
                'requirements' => [
                    'NCA-registered contractor (Category 1-3)',
                    'Proven experience in rural infrastructure',
                    'Community engagement capacity',
                ],
                'reference_number' => 'TND-2026-019-CID',
                'tender_type' => 'RFP',
                'entity_name' => 'KURA',
                'sector' => 'Communities & Infrastructure',
                'procuring_entity' => 'Kenya Urban Roads Authority',
                'country_region' => 'Kenya',
                'location' => 'Eastern Region, Kenya',
                'start_date' => $today->copy()->subDays(2)->toDateString(),
                'end_date' => $today->copy()->addMonths(4)->toDateString(),
                'amount' => 3750000,
                'budget_min' => 3500000,
                'budget_max' => 4000000,
                'currency' => 'USD',
                'submission_method' => 'Physical submission at KURA headquarters',
                'required_documents' => [
                    'NCA registration certificate',
                    'Company profile and past projects',
                    'Methodology and work plan',
                    'Equipment list and availability',
                    'Key personnel CVs and certifications',
                    'Environmental and social management plan',
                ],
                'eligibility_criteria' => [
                    'NCA registered (Category 1-3)',
                    'Completed at least 3 similar projects in the last 5 years',
                    'Available project manager with 10+ years experience',
                    'Access to required construction equipment',
                    'Valid tax compliance and insurance',
                ],
                'attachments' => [
                    ['id' => '1', 'name' => 'Project_Design_Brief.pdf', 'type' => 'PDF', 'size' => '5.8 MB', 'url' => '/documents/tenders/project-design-brief.pdf'],
                    ['id' => '2', 'name' => 'Site_Maps.pdf', 'type' => 'PDF', 'size' => '12.4 MB', 'url' => '/documents/tenders/site-maps.pdf'],
                    ['id' => '3', 'name' => 'BoQ_Template.xlsx', 'type' => 'Excel', 'size' => '345 KB', 'url' => '/documents/tenders/boq-template.xlsx'],
                    ['id' => '4', 'name' => 'Environmental_Guidelines.pdf', 'type' => 'PDF', 'size' => '1.2 MB', 'url' => '/documents/tenders/environmental-guidelines.pdf'],
                ],
                'published_date' => $today->copy()->subDays(2)->toDateString(),
                'clarification_deadline' => $today->copy()->addMonths(2)->toDateString(),
                'submission_deadline' => $today->copy()->addMonths(4)->toDateString(),
                'status' => 'active',
                'views_count' => 278,
                'applications_count' => 9,
            ],
            [
                'title' => 'Information Technology Systems Upgrade',
                'description' => 'Supply, installation, and commissioning of enterprise IT systems including hardware, software, and training for staff.',
                'summary' => 'Complete IT infrastructure modernisation for 12 government offices across two cities.',
                'scope_of_work' => 'Supply and install enterprise servers, networking equipment, workstations, and UPS systems. Deploy and configure ERP software, email systems, and cybersecurity solutions. Provide comprehensive staff training and 2-year support contract.',
                'requirements' => [
                    'Certified IT solutions provider',
                    'OEM partnership or authorised reseller',
                    'Minimum 5 years enterprise IT experience',
                ],
                'reference_number' => 'TND-2026-021-IT',
                'tender_type' => 'RFQ',
                'entity_name' => 'ICT Authority',
                'sector' => 'Information Technology',
                'procuring_entity' => 'ICT Authority Kenya',
                'country_region' => 'Kenya',
                'location' => 'Nairobi & Mombasa',
                'start_date' => $today->copy()->toDateString(),
                'end_date' => $today->copy()->addMonths(3)->addWeeks(1)->toDateString(),
                'amount' => 900000,
                'budget_min' => 800000,
                'budget_max' => 1000000,
                'currency' => 'USD',
                'submission_method' => 'Online portal submission only',
                'required_documents' => [
                    'OEM partnership certificates',
                    'Technical proposal with architecture diagrams',
                    'Equipment specifications and data sheets',
                    'Implementation timeline',
                    'Training plan',
                    'Post-deployment support plan',
                ],
                'eligibility_criteria' => [
                    'ICT Authority pre-qualified vendor',
                    'ISO 27001 certified or equivalent',
                    'Completed similar project of $500K+ value',
                    'Local support team availability',
                ],
                'attachments' => [
                    ['id' => '1', 'name' => 'Technical_Specifications.pdf', 'type' => 'PDF', 'size' => '4.1 MB', 'url' => '/documents/tenders/technical-specifications.pdf'],
                    ['id' => '2', 'name' => 'Network_Topology.pdf', 'type' => 'PDF', 'size' => '2.7 MB', 'url' => '/documents/tenders/network-topology.pdf'],
                    ['id' => '3', 'name' => 'Current_Inventory.xlsx', 'type' => 'Excel', 'size' => '512 KB', 'url' => '/documents/tenders/current-inventory.xlsx'],
                ],
                'published_date' => $today->copy()->toDateString(),
                'clarification_deadline' => $today->copy()->addMonths(2)->toDateString(),
                'submission_deadline' => $today->copy()->addMonths(3)->addWeeks(1)->toDateString(),
                'status' => 'active',
                'views_count' => 423,
                'applications_count' => 15,
            ],
            [
                'title' => 'Cleaning and Facility Management Services',
                'description' => 'Provision of cleaning, pest control, and general facility management services for government buildings over a 3-year period.',
                'summary' => 'Comprehensive cleaning and facility management for 8 government office buildings in Central Province.',
                'scope_of_work' => 'Daily cleaning of offices, washrooms, and common areas. Weekly deep cleaning and carpet shampooing. Monthly pest control treatments. Waste management and recycling services. Minor maintenance and repairs.',
                'requirements' => [
                    'Registered facility management company',
                    'Minimum 3 years experience in similar contracts',
                    'Adequate staffing capacity',
                ],
                'reference_number' => 'TND-2026-024-CFM',
                'tender_type' => 'EOI',
                'entity_name' => 'State Department for Public Works',
                'sector' => 'Facility Services',
                'procuring_entity' => 'State Department for Public Works',
                'country_region' => 'Kenya',
                'location' => 'Central Province, Kenya',
                'start_date' => $today->copy()->toDateString(),
                'end_date' => $today->copy()->addMonths(2)->toDateString(),
                'amount' => 360000,
                'budget_min' => 320000,
                'budget_max' => 400000,
                'currency' => 'USD',
                'submission_method' => 'Physical and electronic submission',
                'required_documents' => [
                    'Company registration documents',
                    'List of current and past contracts',
                    'Staff deployment plan',
                    'Equipment and chemicals inventory',
                    'Health and safety policy',
                ],
                'eligibility_criteria' => [
                    'Registered with relevant regulatory body',
                    'At least 3 active facility management contracts',
                    'Staff trained in occupational health and safety',
                    'Public liability insurance',
                ],
                'attachments' => [
                    ['id' => '1', 'name' => 'Building_Specifications.pdf', 'type' => 'PDF', 'size' => '1.8 MB', 'url' => '/documents/tenders/building-specifications.pdf'],
                    ['id' => '2', 'name' => 'Service_Level_Agreement.pdf', 'type' => 'PDF', 'size' => '640 KB', 'url' => '/documents/tenders/service-level-agreement.pdf'],
                ],
                'published_date' => $today->copy()->toDateString(),
                'clarification_deadline' => $today->copy()->addWeeks(4)->toDateString(),
                'submission_deadline' => $today->copy()->addMonths(2)->toDateString(),
                'status' => 'pending_approval',
                'views_count' => 95,
                'applications_count' => 0,
            ],
            [
                'title' => 'Construction of Regional Office Block',
                'description' => 'Construction of a 4-storey office block with associated works including parking, landscaping, and utilities connections.',
                'summary' => 'New 4-storey office block for the regional administration headquarters.',
                'scope_of_work' => 'Full construction including foundations, structural works, MEP installations, interior finishing, external works (parking, fencing, landscaping), and utilities connections. Includes architectural and structural supervision throughout.',
                'requirements' => [
                    'NCA registered contractor (Category 1)',
                    'Proof of completed buildings of similar scale',
                    'Performance bond capability',
                ],
                'reference_number' => 'TND-2026-001-CON',
                'tender_type' => 'ITB',
                'entity_name' => 'BuildCo Ltd',
                'sector' => 'Construction',
                'procuring_entity' => 'County Government of Nairobi',
                'country_region' => 'Kenya',
                'location' => 'Nairobi',
                'start_date' => $today->copy()->subYear()->toDateString(),
                'end_date' => $today->copy()->subMonths(10)->toDateString(),
                'amount' => 499000,
                'budget_min' => 450000,
                'budget_max' => 550000,
                'currency' => 'USD',
                'submission_method' => 'Physical submission at county offices',
                'required_documents' => [
                    'NCA registration (Category 1)',
                    'Audited financial statements (3 years)',
                    'Bank guarantee letter',
                    'Priced Bill of Quantities',
                    'Construction methodology',
                    'Project schedule (Gantt chart)',
                ],
                'eligibility_criteria' => [
                    'NCA Category 1 registration',
                    'Completed at least 2 buildings of 3+ floors',
                    'Bond capacity of at least 10% of tender sum',
                    'Valid tax compliance certificate',
                    'No debarment from public procurement',
                ],
                'attachments' => [
                    ['id' => '1', 'name' => 'Architectural_Drawings.pdf', 'type' => 'PDF', 'size' => '18.5 MB', 'url' => '/documents/tenders/architectural-drawings.pdf'],
                    ['id' => '2', 'name' => 'Structural_Drawings.pdf', 'type' => 'PDF', 'size' => '14.2 MB', 'url' => '/documents/tenders/structural-drawings.pdf'],
                    ['id' => '3', 'name' => 'Bill_of_Quantities.xlsx', 'type' => 'Excel', 'size' => '890 KB', 'url' => '/documents/tenders/bill-of-quantities.xlsx'],
                    ['id' => '4', 'name' => 'Site_Survey_Report.pdf', 'type' => 'PDF', 'size' => '3.4 MB', 'url' => '/documents/tenders/site-survey-report.pdf'],
                ],
                'published_date' => $today->copy()->subYear()->toDateString(),
                'clarification_deadline' => $today->copy()->subMonths(11)->toDateString(),
                'submission_deadline' => $today->copy()->subMonths(10)->toDateString(),
                'status' => 'expired',
                'views_count' => 612,
                'applications_count' => 31,
            ],
            [
                'title' => 'Supply and Installation of Solar Power Systems',
                'description' => 'Design, supply, installation, and commissioning of off-grid solar power systems for 20 rural health centres and schools across the Rift Valley region.',
                'summary' => 'Off-grid solar electrification project covering 20 rural health centres and schools in Rift Valley.',
                'scope_of_work' => 'Site assessment and system design for each facility. Supply and install solar panels, inverters, battery banks, and distribution boards. Provide lightning protection, earthing, and wiring. Commission all systems and train facility staff on basic maintenance. Include 3-year warranty and maintenance contract.',
                'requirements' => [
                    'Licensed electrical contractor (Class A)',
                    'ERC-registered solar installer',
                    'Minimum 3 completed solar projects of similar scope',
                    'Capacity to deploy across multiple sites simultaneously',
                ],
                'reference_number' => 'TND-2026-030-SOL',
                'tender_type' => 'RFP',
                'entity_name' => 'Rural Electrification and Renewable Energy Corporation',
                'sector' => 'Energy & Renewables',
                'procuring_entity' => 'REREC Kenya',
                'country_region' => 'Kenya',
                'location' => 'Rift Valley, Kenya',
                'start_date' => $today->copy()->toDateString(),
                'end_date' => $today->copy()->addMonths(5)->toDateString(),
                'amount' => 1800000,
                'budget_min' => 1500000,
                'budget_max' => 2000000,
                'currency' => 'USD',
                'submission_method' => 'Online portal submission only',
                'required_documents' => [
                    'ERC solar installer licence',
                    'Company profile and audited accounts (2 years)',
                    'Technical proposal with system designs',
                    'Equipment datasheets and certifications',
                    'Implementation and logistics plan',
                    'Warranty and maintenance proposal',
                ],
                'eligibility_criteria' => [
                    'ERC-registered solar energy company',
                    'Completed at least 3 off-grid solar projects valued above $200K each',
                    'Certified electrical engineers on staff',
                    'Valid tax compliance certificate',
                    'Public liability and professional indemnity insurance',
                ],
                'attachments' => [
                    ['id' => '1', 'name' => 'Site_List_and_Coordinates.xlsx', 'type' => 'Excel', 'size' => '128 KB', 'url' => '/documents/tenders/site-list-coordinates.xlsx'],
                    ['id' => '2', 'name' => 'Technical_Specifications_Solar.pdf', 'type' => 'PDF', 'size' => '3.6 MB', 'url' => '/documents/tenders/technical-specifications-solar.pdf'],
                    ['id' => '3', 'name' => 'Sample_System_Design.pdf', 'type' => 'PDF', 'size' => '2.1 MB', 'url' => '/documents/tenders/sample-system-design.pdf'],
                    ['id' => '4', 'name' => 'Maintenance_SLA_Template.pdf', 'type' => 'PDF', 'size' => '480 KB', 'url' => '/documents/tenders/maintenance-sla-template.pdf'],
                ],
                'published_date' => $today->copy()->toDateString(),
                'clarification_deadline' => $today->copy()->addMonths(2)->toDateString(),
                'submission_deadline' => $today->copy()->addMonths(5)->toDateString(),
                'status' => 'pending_approval',
                'views_count' => 47,
                'applications_count' => 0,
            ],
            [
                'title' => 'Marine Conservation Patrol Vessel Supply',
                'description' => 'Supply of two coastal patrol vessels for marine protected area enforcement around Mahe and Praslin.',
                'summary' => 'Procurement of coastal patrol vessels and onboard monitoring equipment for marine conservation.',
                'scope_of_work' => 'Design confirmation, supply, delivery, sea trials, crew training, and 24-month maintenance support.',
                'requirements' => [
                    'Certified marine vessel supplier',
                    'Local after-sales support capability',
                    'Compliance with Seychelles maritime standards',
                ],
                'reference_number' => 'TND-SCR-2026-041-MAR',
                'tender_type' => 'RFQ',
                'entity_name' => 'Seychelles Parks and Gardens Authority',
                'sector' => 'Environment & Marine',
                'procuring_entity' => 'SPGA',
                'country_region' => 'Seychelles',
                'location' => 'Mahe',
                'start_date' => $today->copy()->subDays(1)->toDateString(),
                'end_date' => $today->copy()->addMonths(2)->toDateString(),
                'amount' => 850000,
                'budget_min' => 700000,
                'budget_max' => 950000,
                'currency' => 'SCR',
                'submission_method' => 'Online portal submission only',
                'required_documents' => [
                    'Company registration',
                    'Vessel specifications',
                    'Warranty terms',
                    'Delivery schedule',
                ],
                'eligibility_criteria' => [
                    'Registered marine supplier',
                    'At least 2 similar vessel deliveries in the last 5 years',
                ],
                'attachments' => [
                    ['id' => '1', 'name' => 'Vessel_Specs.pdf', 'type' => 'PDF', 'size' => '2.0 MB', 'url' => '/documents/tenders/vessel-specs.pdf'],
                ],
                'published_date' => $today->copy()->subDays(1)->toDateString(),
                'clarification_deadline' => $today->copy()->addWeeks(3)->toDateString(),
                'submission_deadline' => $today->copy()->addMonths(2)->toDateString(),
                'status' => 'active',
                'views_count' => 88,
                'applications_count' => 4,
            ],
            [
                'title' => 'Tourism Skills Training Programme Framework',
                'description' => 'Framework agreement for hospitality and tourism short courses delivered across Mahe, Praslin and La Digue.',
                'summary' => 'Multi-island tourism skills training framework for job seekers and industry upskilling.',
                'scope_of_work' => 'Curriculum delivery, trainer deployment, assessment, certification, and quarterly reporting.',
                'requirements' => [
                    'Accredited training provider',
                    'Hospitality trainers with industry experience',
                ],
                'reference_number' => 'TND-SCR-2026-055-TRN',
                'tender_type' => 'RFP',
                'entity_name' => 'Seychelles Tourism Academy',
                'sector' => 'Education & Training',
                'procuring_entity' => 'Ministry of Tourism',
                'country_region' => 'Seychelles',
                'location' => 'Mahe',
                'start_date' => $today->copy()->toDateString(),
                'end_date' => $today->copy()->addMonths(6)->toDateString(),
                'amount' => 420000,
                'budget_min' => 350000,
                'budget_max' => 480000,
                'currency' => 'SCR',
                'submission_method' => 'Physical and electronic submission',
                'required_documents' => [
                    'Accreditation certificates',
                    'Trainer CVs',
                    'Course outlines',
                    'Financial proposal',
                ],
                'eligibility_criteria' => [
                    'Accredited training institution',
                    'Ability to deliver on three islands',
                ],
                'attachments' => [
                    ['id' => '1', 'name' => 'Training_Framework.pdf', 'type' => 'PDF', 'size' => '1.4 MB', 'url' => '/documents/tenders/training-framework.pdf'],
                ],
                'published_date' => $today->copy()->toDateString(),
                'clarification_deadline' => $today->copy()->addMonth()->toDateString(),
                'submission_deadline' => $today->copy()->addMonths(6)->toDateString(),
                'status' => 'active',
                'views_count' => 64,
                'applications_count' => 2,
            ],
        ];

        foreach ($tenders as $data) {
            $slug = Str::slug($data['title']);
            $baseSlug = $slug;
            $i = 0;
            while (TenderAd::where('slug', $slug)->exists()) {
                $slug = $baseSlug.'-'.(++$i);
            }

            TenderAd::create(array_merge($data, [
                'slug' => $slug,
                'category_id' => $catId,
                'created_by' => null,
            ]));
        }
    }
}
